package analizador_lexico;

public class AnalizadorLexico {
	
	private static enum Estado {
		END_FINDEC,
		END_SEP,
		END_TIPO,
		END_INT,
		END_REAL,
		END_CAP,
		END_CCIERRE,
		END_REC,
		END_ENDREC,
		END_POINTER,
		END_OBJECT,
		END_EXTENDS,
		END_VAR,
		END_END,
		END_FUN,
		END_METHOD,
		END_RETURNS,
		END_THIS,
		END_SUPER,
		END_PUNTO,
		END_APUNTADOR,
		END_MENOR,
		END_MAYOR,
		END_MENORIGUAL,
		END_MAYORIGUAL,
		END_IGUAL,
		END_DISTINTO,
		END_OR,
		END_MAS,
		END_MENOS,
		END_POR,
		END_DIV,
		END_MOD,
		END_AND,
		END_NOT,
		END_PAP,
		END_PCIERRE,
		END_NULL,
		END_LITENTPOS,
		END_ASIGN,
		END_IN,
		END_OUT,
		END_ALLOC,
		END_FREE,
		END_IF,
		END_ELSE,
		END_ELSEIF,
		END_THEN,
		END_ENDIF,
		END_WHILE,
		END_DO,
		END_ENDWHILE,
		END_CARACTER,
		/*Clases auxiliares*/
		END_DIGITO,
		END_DIGITOPOS,
		END_BARRABAJA,
		END_EOF
	}
}
